# Test goal: build with hipSYCL (both CUDA and ROCm backends) to check SYCL code compatibility
# Test intents (should change rarely and conservatively):
#   OS: Ubuntu newest supported
#   Compiler: Clang newest supported
#   GPU: hipSYCL
#   Scope: configure, build
# Test implementation choices (free to change as needed):
#   OS: Ubuntu 20.04
#   Build type: RelWithAssert
#   Compiler: Clang 11
#   MPI: thread_MPI
#   SIMD: AVX2_256

gromacs:hipsycl-dev:configure:
  extends:
    - .gromacs:base:configure
    - .use-clang:base
    - .use-sycl
    - .rules:merge-and-post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-11-cuda-11.0
  variables:
    CMAKE: /usr/local/cmake-3.13.0/bin/cmake
    CMAKE_COMPILER_SCRIPT: "-DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang"
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=AVX2_256"
    CMAKE_BUILD_TYPE_OPTIONS: "-DCMAKE_BUILD_TYPE=RelWithAssert"
    CMAKE_EXTRA_OPTIONS: "-DGMX_SYCL_HIPSYCL=ON"
    COMPILER_MAJOR_VERSION: 11

gromacs:hipsycl-dev:build:
  extends:
    - .variables:default
    - .gromacs:base:build
    - .before_script:default
    - .use-ccache
    - .rules:merge-and-post-merge-acceptance
  image: ${CI_REGISTRY}/gromacs/gromacs/ci-ubuntu-20.04-llvm-11-cuda-11.0
  variables:
    CMAKE: /usr/local/cmake-3.13.0/bin/cmake
  tags:
    - k8s-scilifelab
  needs:
    - job: gromacs:hipsycl-dev:configure

